apiVersion: v1
kind: ConfigMap
metadata:
  name: www
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>hello</title>
      </head>
      <body>
        Hello, world!
      </body>
    </html>
