apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: default
  labels:
    run: busybox
spec:
  replicas: 2
  selector:
    matchLabels:
      run: busybox
  template:
    metadata:
      labels:
        run: busybox
    spec:
      containers:
        - name: busybox
          image: busybox
          imagePullPolicy: Always
          args: ["httpd", "-f", "-p", "8000", "-h", "/var/www"]
          ports:
            - name: target
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: www-volume
              mountPath: /var/www
      restartPolicy: Always
      securityContext:
        runAsUser: 10000
      volumes:
        - name: www-volume
          configMap:
            name: www
---
apiVersion: v1
kind: Service
metadata:
  name: busybox
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 103.79.13.210
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: busybox
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: www
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>hello</title>
      </head>
      <body>
        Hello, world!
      </body>
    </html>
